### ISSUE TITLE
Cant render

### ISSUE THREAD

**Issue by SPAWNRYS-ban** [alexhliu/ChunkyClPlugin#14]
CPU: amd Ryzen 5 1600
GPU: Nvidia GeForce GTX 1050 TI
![Screenshot_2222](https://user-images.githubusercontent.com/68144848/122299841-2f498480-cf07-11eb-8d55-b03c36e39187.png)

**Comment by y0ngh0** [comment]
I have the same thing

**Comment by alexhliu** [comment]
Did you select ChunkyCl as your renderer for the scene?

![image](https://user-images.githubusercontent.com/42661490/122492297-5d2bd900-cf9a-11eb-954e-14d772ed3898.png)

Are there any errors in the debug console?

Can you try the latest build?

**Comment by y0ngh0** [comment]
I got it working. Thanks for the help.
